/**
 * APIMATICCalculatorLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

;(function (angular) {
'use strict';

angular.module('APIMATICCalculatorLib')
    .factory('Servers', [ServersModel]);

    function ServersModel() {
        return {
            //TODO: Write general description for this element
            ORACLE: 'Oracle',
    
            //TODO: Write general description for this element
            API_MATIC_HOST: 'APIMaticHost'
        };
    }

}(angular));
